# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        pretty
baseurl:          /gloo

# Server
destination:      ./doc
exclude:          []
port:             9001

# Custom vars
repo:             https://github.com/greenled/gloo
download_zip:     https://github.com/greenled/gloo/zipball/master
download_tar:     https://github.com/greenled/gloo/tarball/master

url:              http://greenled.github.io/gloo
twitter:          http://www.twitter.com/greenled2013
dreamcatchers:    http://dreamcatchers.reduc.edu.cu/prefil/greenLED
